name: Build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "23.x"
          elixir-version: "1.11.4"

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build

      - name: Cache .mix
        uses: actions/cache@v2
        with:
          path: ~/.mix
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix

      - name: Get deps
        run: mix deps.get
        env:
          MIX_ENV: test

      - name: Mix format
        run: mix format --check-formatted
        env:
          MIX_ENV: test

      - name: Mix credo
        run: mix credo
        env:
          MIX_ENV: test

      - name: test
        run: mix coveralls.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./cover/excoveralls.json
          fail_ci_if_error: true
